const RESET_GAME = "RESET_GAME";
const MOVE = "MOVE";
const AIPLAY = "AIPLAY";
const CHECK_WIN = "CHECK_WIN";
const SET_WINNER = "SET_WINNER";
const SET_GAMETIE = "SET_GAMETIE";
const CHANGEPALYER = "CHANGEPALYER";
export {
  RESET_GAME,
  MOVE,
  AIPLAY,
  CHECK_WIN,
  SET_WINNER,
  SET_GAMETIE,
  CHANGEPALYER
};
